# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

postgres:
  adapter: postgresql
  database: users
  username: postgres
  password: postgres

before_script:
  - psql -c "create schema public;" -U postgres
  - psql -c 'create database users;' -U postgres
  - rake db:migrate

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - shonorov@gmail.com
    on_success: never # default: change
    on_failure: never # default: always
